/* tslint:disable */
/* eslint-disable */
/**
 * E-Clubs | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AttendanceHistoryResponse {
    'date'?: string;
    'status'?: string;
}
export interface CreateClubRequest {
    'name'?: string;
    'professorId'?: string;
    'day'?: number;
    'startTime'?: string;
    'endTime'?: string;
}
export interface CreateMessageRequest {
    'senderId'?: string;
    'content'?: string;
}
export interface CreateWorkPlanRequest {
    'domain'?: string;
    'unit'?: string;
    'learningOutcome'?: string;
    'indicator'?: string;
    'scheduledDate'?: string;
}
export interface GetAttendanceResponse {
    'student': GetUserResponse;
    'attendanceHistory': Array<AttendanceHistoryResponse>;
}
export interface GetClubResponse {
    'id'?: string;
    'professor'?: GetUserResponse;
    'name'?: string;
    'code'?: string;
    'day'?: number;
    'startTime'?: string;
    'endTime'?: string;
}
export interface GetDomainsResponse {
    'domainNumber'?: number;
    'domain'?: string;
}
export interface GetMeResponse {
    'id'?: string;
    'firstName'?: string;
    'lastName'?: string;
    'roles'?: Array<string>;
}
export interface GetMessageResponse {
    'id'?: string;
    'sender': GetUserResponse;
    'content'?: string;
    'sentAt'?: string;
}
export interface GetUserResponse {
    'id'?: string;
    'firstName'?: string;
    'lastName'?: string;
}
export interface GetWorkPlanResponse {
    'id'?: string;
    'domain'?: string;
    'unit'?: string;
    'learningOutcome'?: string;
    'indicator'?: string;
    'realizationDate'?: string | null;
}
export interface JoinClubRequest {
    'studentId'?: string;
    'code'?: string;
}
export interface KickStudentRequest {
    'studentId'?: string;
}
export interface LoginUserRequest {
    'mail'?: string;
    'password'?: string;
}
export interface ProblemDetails {
    'type'?: string | null;
    'title'?: string | null;
    'status'?: number | null;
    'detail'?: string | null;
    'instance'?: string | null;
}
export interface RegisterAttendanceRequest {
    'studentId'?: string;
    'date'?: string;
    'status'?: number;
}
export interface RegisterUserRequest {
    'firstName'?: string;
    'lastName'?: string;
    'mail'?: string;
    'password'?: string;
}
export interface UpdateMessageRequest {
    'content'?: string;
}

/**
 * AttendancesApi - axios parameter creator
 */
export const AttendancesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendancesForClub: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getAttendancesForClub', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/Attendances`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserAttendancesForClub: async (clubId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getUserAttendancesForClub', 'clubId', clubId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserAttendancesForClub', 'userId', userId)
            const localVarPath = `/api/clubs/{clubId}/Attendances/{userId}`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)))
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {RegisterAttendanceRequest} registerAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markStudentPresent: async (clubId: string, registerAttendanceRequest: RegisterAttendanceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('markStudentPresent', 'clubId', clubId)
            // verify required parameter 'registerAttendanceRequest' is not null or undefined
            assertParamExists('markStudentPresent', 'registerAttendanceRequest', registerAttendanceRequest)
            const localVarPath = `/api/clubs/{clubId}/Attendances`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerAttendanceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AttendancesApi - functional programming interface
 */
export const AttendancesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AttendancesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAttendancesForClub(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAttendanceResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAttendancesForClub(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendancesApi.getAttendancesForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserAttendancesForClub(clubId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAttendanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserAttendancesForClub(clubId, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendancesApi.getUserAttendancesForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {RegisterAttendanceRequest} registerAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markStudentPresent(clubId: string, registerAttendanceRequest: RegisterAttendanceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markStudentPresent(clubId, registerAttendanceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendancesApi.markStudentPresent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AttendancesApi - factory interface
 */
export const AttendancesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AttendancesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendancesForClub(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetAttendanceResponse>> {
            return localVarFp.getAttendancesForClub(clubId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserAttendancesForClub(clubId: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAttendanceResponse> {
            return localVarFp.getUserAttendancesForClub(clubId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {RegisterAttendanceRequest} registerAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markStudentPresent(clubId: string, registerAttendanceRequest: RegisterAttendanceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.markStudentPresent(clubId, registerAttendanceRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AttendancesApi - object-oriented interface
 */
export class AttendancesApi extends BaseAPI {
    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAttendancesForClub(clubId: string, options?: RawAxiosRequestConfig) {
        return AttendancesApiFp(this.configuration).getAttendancesForClub(clubId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserAttendancesForClub(clubId: string, userId: string, options?: RawAxiosRequestConfig) {
        return AttendancesApiFp(this.configuration).getUserAttendancesForClub(clubId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {RegisterAttendanceRequest} registerAttendanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markStudentPresent(clubId: string, registerAttendanceRequest: RegisterAttendanceRequest, options?: RawAxiosRequestConfig) {
        return AttendancesApiFp(this.configuration).markStudentPresent(clubId, registerAttendanceRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMe: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LoginUserRequest} loginUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser: async (loginUserRequest: LoginUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginUserRequest' is not null or undefined
            assertParamExists('loginUser', 'loginUserRequest', loginUserRequest)
            const localVarPath = `/api/Auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RegisterUserRequest} registerUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (registerUserRequest: RegisterUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerUserRequest' is not null or undefined
            assertParamExists('registerUser', 'registerUserRequest', registerUserRequest)
            const localVarPath = `/api/Auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMe(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMe(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.getMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LoginUserRequest} loginUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUser(loginUserRequest: LoginUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUser(loginUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RegisterUserRequest} registerUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(registerUserRequest: RegisterUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(registerUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.registerUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMe(options?: RawAxiosRequestConfig): AxiosPromise<GetMeResponse> {
            return localVarFp.getMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LoginUserRequest} loginUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(loginUserRequest: LoginUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.loginUser(loginUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RegisterUserRequest} registerUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(registerUserRequest: RegisterUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.registerUser(registerUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMe(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).getMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LoginUserRequest} loginUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public loginUser(loginUserRequest: LoginUserRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginUser(loginUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RegisterUserRequest} registerUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerUser(registerUserRequest: RegisterUserRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).registerUser(registerUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ClubMessagesApi - axios parameter creator
 */
export const ClubMessagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessagesByClubId: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getMessagesByClubId', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/ClubMessages`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {CreateMessageRequest} createMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessage: async (clubId: string, createMessageRequest: CreateMessageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('sendMessage', 'clubId', clubId)
            // verify required parameter 'createMessageRequest' is not null or undefined
            assertParamExists('sendMessage', 'createMessageRequest', createMessageRequest)
            const localVarPath = `/api/clubs/{clubId}/ClubMessages`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMessageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClubMessagesApi - functional programming interface
 */
export const ClubMessagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ClubMessagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessagesByClubId(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetMessageResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessagesByClubId(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubMessagesApi.getMessagesByClubId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {CreateMessageRequest} createMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendMessage(clubId: string, createMessageRequest: CreateMessageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendMessage(clubId, createMessageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubMessagesApi.sendMessage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ClubMessagesApi - factory interface
 */
export const ClubMessagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ClubMessagesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessagesByClubId(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetMessageResponse>> {
            return localVarFp.getMessagesByClubId(clubId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {CreateMessageRequest} createMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessage(clubId: string, createMessageRequest: CreateMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetMessageResponse> {
            return localVarFp.sendMessage(clubId, createMessageRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ClubMessagesApi - object-oriented interface
 */
export class ClubMessagesApi extends BaseAPI {
    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMessagesByClubId(clubId: string, options?: RawAxiosRequestConfig) {
        return ClubMessagesApiFp(this.configuration).getMessagesByClubId(clubId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {CreateMessageRequest} createMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendMessage(clubId: string, createMessageRequest: CreateMessageRequest, options?: RawAxiosRequestConfig) {
        return ClubMessagesApiFp(this.configuration).sendMessage(clubId, createMessageRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ClubsApi - axios parameter creator
 */
export const ClubsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {JoinClubRequest} joinClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addStudentToClub: async (joinClubRequest: JoinClubRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'joinClubRequest' is not null or undefined
            assertParamExists('addStudentToClub', 'joinClubRequest', joinClubRequest)
            const localVarPath = `/api/Clubs/join`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(joinClubRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateClubRequest} createClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createClub: async (createClubRequest: CreateClubRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createClubRequest' is not null or undefined
            assertParamExists('createClub', 'createClubRequest', createClubRequest)
            const localVarPath = `/api/Clubs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createClubRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {KickStudentRequest} kickStudentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStudentFromClub: async (clubId: string, kickStudentRequest: KickStudentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('deleteStudentFromClub', 'clubId', clubId)
            // verify required parameter 'kickStudentRequest' is not null or undefined
            assertParamExists('deleteStudentFromClub', 'kickStudentRequest', kickStudentRequest)
            const localVarPath = `/api/Clubs/{clubId}/students`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(kickStudentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClubById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getClubById', 'id', id)
            const localVarPath = `/api/Clubs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClubsForUser: async (userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Clubs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['UserId'] = userId;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentsInClub: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getStudentsInClub', 'clubId', clubId)
            const localVarPath = `/api/Clubs/{clubId}/students`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClubsApi - functional programming interface
 */
export const ClubsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ClubsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {JoinClubRequest} joinClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addStudentToClub(joinClubRequest: JoinClubRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addStudentToClub(joinClubRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.addStudentToClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateClubRequest} createClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createClub(createClubRequest: CreateClubRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetClubResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createClub(createClubRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.createClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {KickStudentRequest} kickStudentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteStudentFromClub(clubId: string, kickStudentRequest: KickStudentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteStudentFromClub(clubId, kickStudentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.deleteStudentFromClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClubById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetClubResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClubById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.getClubById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClubsForUser(userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetClubResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClubsForUser(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.getClubsForUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStudentsInClub(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetUserResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStudentsInClub(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.getStudentsInClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ClubsApi - factory interface
 */
export const ClubsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ClubsApiFp(configuration)
    return {
        /**
         * 
         * @param {JoinClubRequest} joinClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addStudentToClub(joinClubRequest: JoinClubRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addStudentToClub(joinClubRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateClubRequest} createClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createClub(createClubRequest: CreateClubRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetClubResponse> {
            return localVarFp.createClub(createClubRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {KickStudentRequest} kickStudentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStudentFromClub(clubId: string, kickStudentRequest: KickStudentRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteStudentFromClub(clubId, kickStudentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClubById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<GetClubResponse> {
            return localVarFp.getClubById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClubsForUser(userId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetClubResponse>> {
            return localVarFp.getClubsForUser(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentsInClub(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetUserResponse>> {
            return localVarFp.getStudentsInClub(clubId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ClubsApi - object-oriented interface
 */
export class ClubsApi extends BaseAPI {
    /**
     * 
     * @param {JoinClubRequest} joinClubRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addStudentToClub(joinClubRequest: JoinClubRequest, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).addStudentToClub(joinClubRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateClubRequest} createClubRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createClub(createClubRequest: CreateClubRequest, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).createClub(createClubRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {KickStudentRequest} kickStudentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteStudentFromClub(clubId: string, kickStudentRequest: KickStudentRequest, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).deleteStudentFromClub(clubId, kickStudentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getClubById(id: string, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).getClubById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [userId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getClubsForUser(userId?: string, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).getClubsForUser(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStudentsInClub(clubId: string, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).getStudentsInClub(clubId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MessagesApi - axios parameter creator
 */
export const MessagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [messageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMessageById: async (messageId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Messages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (messageId !== undefined) {
                localVarQueryParameter['messageId'] = messageId;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} messageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessageById: async (messageId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'messageId' is not null or undefined
            assertParamExists('getMessageById', 'messageId', messageId)
            const localVarPath = `/api/Messages/{messageId}`
                .replace(`{${"messageId"}}`, encodeURIComponent(String(messageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} messageId 
         * @param {UpdateMessageRequest} updateMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMessageById: async (messageId: string, updateMessageRequest: UpdateMessageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'messageId' is not null or undefined
            assertParamExists('updateMessageById', 'messageId', messageId)
            // verify required parameter 'updateMessageRequest' is not null or undefined
            assertParamExists('updateMessageById', 'updateMessageRequest', updateMessageRequest)
            const localVarPath = `/api/Messages/{messageId}`
                .replace(`{${"messageId"}}`, encodeURIComponent(String(messageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateMessageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessagesApi - functional programming interface
 */
export const MessagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [messageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMessageById(messageId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMessageById(messageId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.deleteMessageById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} messageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessageById(messageId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessageById(messageId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.getMessageById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} messageId 
         * @param {UpdateMessageRequest} updateMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMessageById(messageId: string, updateMessageRequest: UpdateMessageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMessageById(messageId, updateMessageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.updateMessageById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MessagesApi - factory interface
 */
export const MessagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessagesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [messageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMessageById(messageId?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteMessageById(messageId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} messageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessageById(messageId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetMessageResponse> {
            return localVarFp.getMessageById(messageId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} messageId 
         * @param {UpdateMessageRequest} updateMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMessageById(messageId: string, updateMessageRequest: UpdateMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateMessageById(messageId, updateMessageRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MessagesApi - object-oriented interface
 */
export class MessagesApi extends BaseAPI {
    /**
     * 
     * @param {string} [messageId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteMessageById(messageId?: string, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).deleteMessageById(messageId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} messageId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMessageById(messageId: string, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).getMessageById(messageId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} messageId 
     * @param {UpdateMessageRequest} updateMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateMessageById(messageId: string, updateMessageRequest: UpdateMessageRequest, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).updateMessageById(messageId, updateMessageRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WorkPlansApi - axios parameter creator
 */
export const WorkPlansApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {Array<CreateWorkPlanRequest>} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batchCreateWorkPlanForClub: async (clubId: string, createWorkPlanRequest: Array<CreateWorkPlanRequest>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('batchCreateWorkPlanForClub', 'clubId', clubId)
            // verify required parameter 'createWorkPlanRequest' is not null or undefined
            assertParamExists('batchCreateWorkPlanForClub', 'createWorkPlanRequest', createWorkPlanRequest)
            const localVarPath = `/api/clubs/{clubId}/WorkPlans/batch`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createWorkPlanRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {CreateWorkPlanRequest} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWorkPlanForClub: async (clubId: string, createWorkPlanRequest: CreateWorkPlanRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('createWorkPlanForClub', 'clubId', clubId)
            // verify required parameter 'createWorkPlanRequest' is not null or undefined
            assertParamExists('createWorkPlanForClub', 'createWorkPlanRequest', createWorkPlanRequest)
            const localVarPath = `/api/clubs/{clubId}/WorkPlans`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createWorkPlanRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentWorkPlan: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getCurrentWorkPlan', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/WorkPlans/current`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDomainsByClubId: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getDomainsByClubId', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/WorkPlans/domains`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkPlansForClub: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getWorkPlansForClub', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/WorkPlans`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadWorkPlansForClub: async (clubId: string, file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('uploadWorkPlansForClub', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/WorkPlans/upload`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkPlansApi - functional programming interface
 */
export const WorkPlansApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WorkPlansApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {Array<CreateWorkPlanRequest>} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async batchCreateWorkPlanForClub(clubId: string, createWorkPlanRequest: Array<CreateWorkPlanRequest>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.batchCreateWorkPlanForClub(clubId, createWorkPlanRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkPlansApi.batchCreateWorkPlanForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {CreateWorkPlanRequest} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createWorkPlanForClub(clubId: string, createWorkPlanRequest: CreateWorkPlanRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetWorkPlanResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createWorkPlanForClub(clubId, createWorkPlanRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkPlansApi.createWorkPlanForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentWorkPlan(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetWorkPlanResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentWorkPlan(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkPlansApi.getCurrentWorkPlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDomainsByClubId(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetDomainsResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDomainsByClubId(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkPlansApi.getDomainsByClubId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWorkPlansForClub(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetWorkPlanResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkPlansForClub(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkPlansApi.getWorkPlansForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadWorkPlansForClub(clubId: string, file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadWorkPlansForClub(clubId, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkPlansApi.uploadWorkPlansForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WorkPlansApi - factory interface
 */
export const WorkPlansApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WorkPlansApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {Array<CreateWorkPlanRequest>} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batchCreateWorkPlanForClub(clubId: string, createWorkPlanRequest: Array<CreateWorkPlanRequest>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.batchCreateWorkPlanForClub(clubId, createWorkPlanRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {CreateWorkPlanRequest} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWorkPlanForClub(clubId: string, createWorkPlanRequest: CreateWorkPlanRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetWorkPlanResponse> {
            return localVarFp.createWorkPlanForClub(clubId, createWorkPlanRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentWorkPlan(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetWorkPlanResponse> {
            return localVarFp.getCurrentWorkPlan(clubId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDomainsByClubId(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetDomainsResponse>> {
            return localVarFp.getDomainsByClubId(clubId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkPlansForClub(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetWorkPlanResponse>> {
            return localVarFp.getWorkPlansForClub(clubId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadWorkPlansForClub(clubId: string, file?: File, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.uploadWorkPlansForClub(clubId, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkPlansApi - object-oriented interface
 */
export class WorkPlansApi extends BaseAPI {
    /**
     * 
     * @param {string} clubId 
     * @param {Array<CreateWorkPlanRequest>} createWorkPlanRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public batchCreateWorkPlanForClub(clubId: string, createWorkPlanRequest: Array<CreateWorkPlanRequest>, options?: RawAxiosRequestConfig) {
        return WorkPlansApiFp(this.configuration).batchCreateWorkPlanForClub(clubId, createWorkPlanRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {CreateWorkPlanRequest} createWorkPlanRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createWorkPlanForClub(clubId: string, createWorkPlanRequest: CreateWorkPlanRequest, options?: RawAxiosRequestConfig) {
        return WorkPlansApiFp(this.configuration).createWorkPlanForClub(clubId, createWorkPlanRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCurrentWorkPlan(clubId: string, options?: RawAxiosRequestConfig) {
        return WorkPlansApiFp(this.configuration).getCurrentWorkPlan(clubId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDomainsByClubId(clubId: string, options?: RawAxiosRequestConfig) {
        return WorkPlansApiFp(this.configuration).getDomainsByClubId(clubId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWorkPlansForClub(clubId: string, options?: RawAxiosRequestConfig) {
        return WorkPlansApiFp(this.configuration).getWorkPlansForClub(clubId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {File} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadWorkPlansForClub(clubId: string, file?: File, options?: RawAxiosRequestConfig) {
        return WorkPlansApiFp(this.configuration).uploadWorkPlansForClub(clubId, file, options).then((request) => request(this.axios, this.basePath));
    }
}



