/* tslint:disable */
/* eslint-disable */
/**
 * E-Clubs | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AttendanceHistoryResponse {
    'date'?: string;
    'status'?: number;
}
export interface AttendanceUserResponse {
    'firstName'?: string;
    'lastName'?: string;
}
export interface ClubMessageResponse {
    'id'?: string;
    'sender': MessageSenderResponse;
    'content'?: string;
    'sentAt'?: string;
}
export interface ClubProfessorResponse {
    'firstName'?: string;
    'lastName'?: string;
}
export interface ClubWorkPlansResponse {
    'id'?: string;
    'title'?: string;
    'description'?: string;
    'note'?: string;
    'status'?: number;
    'scheduledDate'?: string;
    'realizationDate'?: string | null;
}
export interface CreateClubRequest {
    'name'?: string;
    'professorId'?: string;
    'day'?: number;
    'startTime'?: string;
    'endTime'?: string;
}
export interface CreateClubResponse {
    'id'?: string;
    'name'?: string;
    'professor': ClubProfessorResponse;
}
export interface CreateMessageRequest {
    'senderId'?: string;
    'content'?: string;
}
export interface CreateMessageResponse {
    'id'?: string;
    'sender': MessageSenderResponse;
    'content'?: string;
    'sentAt'?: string;
}
export interface CreateWorkPlanRequest {
    'title'?: string;
    'description'?: string;
    'note'?: string;
    'scheduledDate'?: string;
}
export interface CreateWorkPlanResponse {
    'id'?: string;
    'title'?: string;
    'description'?: string;
    'note'?: string;
    'status'?: number;
    'scheduledDate'?: string;
}
export interface GetAllAttendancesResponse {
    'student': AttendanceUserResponse;
    'attendanceHistory': Array<AttendanceHistoryResponse>;
}
export interface GetAllClubsResponse {
    'id'?: string;
    'name'?: string;
    'professor': ClubProfessorResponse;
}
export interface GetAllMessagesByClubIdResponse {
    'id'?: string;
    'sender': MessageSenderResponse;
    'content'?: string;
    'sentAt'?: string;
}
export interface GetAllWorkPlansByClubIdResponse {
    'id'?: string;
    'title'?: string;
    'description'?: string;
    'note'?: string;
    'status'?: number;
    'scheduledDate'?: string;
    'realizationDate'?: string | null;
}
export interface GetClubByIdResponse {
    'id'?: string;
    'name'?: string;
    'day'?: number;
    'startTime'?: string;
    'endTime'?: string;
    'isActive'?: boolean;
    'createdAt'?: string;
    'professor': ClubProfessorResponse;
    'workPlans'?: Array<ClubWorkPlansResponse>;
    'messages'?: Array<ClubMessageResponse>;
}
export interface GetUserAttendanceResponse {
    'student': AttendanceUserResponse;
    'date'?: string;
    'status'?: number;
}
export interface LoginUserRequest {
    'mail'?: string;
    'password'?: string;
}
export interface LoginUserResponse {
    'token'?: string;
}
export interface MessageSenderResponse {
    'id'?: string;
    'firstName'?: string;
    'lastName'?: string;
}
export interface ProblemDetails {
    'type'?: string | null;
    'title'?: string | null;
    'status'?: number | null;
    'detail'?: string | null;
    'instance'?: string | null;
}
export interface RegisterAttendanceRequest {
    'userId'?: string;
}
export interface RegisterUserRequest {
    'firstName'?: string;
    'lastName'?: string;
    'mail'?: string;
    'password'?: string;
}

/**
 * AttendancesApi - axios parameter creator
 */
export const AttendancesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        concludeAttendanceTaking: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('concludeAttendanceTaking', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/Attendances/conclude`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendancesForClub: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getAttendancesForClub', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/Attendances`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserAttendancesForClub: async (clubId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getUserAttendancesForClub', 'clubId', clubId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserAttendancesForClub', 'userId', userId)
            const localVarPath = `/api/clubs/{clubId}/Attendances/{userId}`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)))
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {RegisterAttendanceRequest} registerAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markStudentPresent: async (clubId: string, registerAttendanceRequest: RegisterAttendanceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('markStudentPresent', 'clubId', clubId)
            // verify required parameter 'registerAttendanceRequest' is not null or undefined
            assertParamExists('markStudentPresent', 'registerAttendanceRequest', registerAttendanceRequest)
            const localVarPath = `/api/clubs/{clubId}/Attendances`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerAttendanceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AttendancesApi - functional programming interface
 */
export const AttendancesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AttendancesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async concludeAttendanceTaking(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.concludeAttendanceTaking(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendancesApi.concludeAttendanceTaking']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAttendancesForClub(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAllAttendancesResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAttendancesForClub(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendancesApi.getAttendancesForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserAttendancesForClub(clubId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetUserAttendanceResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserAttendancesForClub(clubId, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendancesApi.getUserAttendancesForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {RegisterAttendanceRequest} registerAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markStudentPresent(clubId: string, registerAttendanceRequest: RegisterAttendanceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markStudentPresent(clubId, registerAttendanceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendancesApi.markStudentPresent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AttendancesApi - factory interface
 */
export const AttendancesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AttendancesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        concludeAttendanceTaking(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.concludeAttendanceTaking(clubId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendancesForClub(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetAllAttendancesResponse>> {
            return localVarFp.getAttendancesForClub(clubId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserAttendancesForClub(clubId: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetUserAttendanceResponse>> {
            return localVarFp.getUserAttendancesForClub(clubId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {RegisterAttendanceRequest} registerAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markStudentPresent(clubId: string, registerAttendanceRequest: RegisterAttendanceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.markStudentPresent(clubId, registerAttendanceRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AttendancesApi - object-oriented interface
 */
export class AttendancesApi extends BaseAPI {
    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public concludeAttendanceTaking(clubId: string, options?: RawAxiosRequestConfig) {
        return AttendancesApiFp(this.configuration).concludeAttendanceTaking(clubId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAttendancesForClub(clubId: string, options?: RawAxiosRequestConfig) {
        return AttendancesApiFp(this.configuration).getAttendancesForClub(clubId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserAttendancesForClub(clubId: string, userId: string, options?: RawAxiosRequestConfig) {
        return AttendancesApiFp(this.configuration).getUserAttendancesForClub(clubId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {RegisterAttendanceRequest} registerAttendanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markStudentPresent(clubId: string, registerAttendanceRequest: RegisterAttendanceRequest, options?: RawAxiosRequestConfig) {
        return AttendancesApiFp(this.configuration).markStudentPresent(clubId, registerAttendanceRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LoginUserRequest} loginUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser: async (loginUserRequest: LoginUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginUserRequest' is not null or undefined
            assertParamExists('loginUser', 'loginUserRequest', loginUserRequest)
            const localVarPath = `/api/Auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RegisterUserRequest} registerUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (registerUserRequest: RegisterUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerUserRequest' is not null or undefined
            assertParamExists('registerUser', 'registerUserRequest', registerUserRequest)
            const localVarPath = `/api/Auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {LoginUserRequest} loginUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUser(loginUserRequest: LoginUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUser(loginUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RegisterUserRequest} registerUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(registerUserRequest: RegisterUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(registerUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.registerUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {LoginUserRequest} loginUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(loginUserRequest: LoginUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginUserResponse> {
            return localVarFp.loginUser(loginUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RegisterUserRequest} registerUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(registerUserRequest: RegisterUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.registerUser(registerUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {LoginUserRequest} loginUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public loginUser(loginUserRequest: LoginUserRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginUser(loginUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RegisterUserRequest} registerUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerUser(registerUserRequest: RegisterUserRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).registerUser(registerUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ClubsApi - axios parameter creator
 */
export const ClubsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateClubRequest} createClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createClub: async (createClubRequest: CreateClubRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createClubRequest' is not null or undefined
            assertParamExists('createClub', 'createClubRequest', createClubRequest)
            const localVarPath = `/api/Clubs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createClubRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClubById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getClubById', 'id', id)
            const localVarPath = `/api/Clubs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClubsForUser: async (userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Clubs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['UserId'] = userId;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClubsApi - functional programming interface
 */
export const ClubsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ClubsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateClubRequest} createClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createClub(createClubRequest: CreateClubRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateClubResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createClub(createClubRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.createClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClubById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetClubByIdResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClubById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.getClubById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClubsForUser(userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAllClubsResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClubsForUser(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClubsApi.getClubsForUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ClubsApi - factory interface
 */
export const ClubsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ClubsApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateClubRequest} createClubRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createClub(createClubRequest: CreateClubRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateClubResponse> {
            return localVarFp.createClub(createClubRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClubById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<GetClubByIdResponse> {
            return localVarFp.getClubById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClubsForUser(userId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetAllClubsResponse>> {
            return localVarFp.getClubsForUser(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ClubsApi - object-oriented interface
 */
export class ClubsApi extends BaseAPI {
    /**
     * 
     * @param {CreateClubRequest} createClubRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createClub(createClubRequest: CreateClubRequest, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).createClub(createClubRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getClubById(id: string, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).getClubById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [userId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getClubsForUser(userId?: string, options?: RawAxiosRequestConfig) {
        return ClubsApiFp(this.configuration).getClubsForUser(userId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MessagesApi - axios parameter creator
 */
export const MessagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {CreateMessageRequest} createMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMessageForClub: async (clubId: string, createMessageRequest: CreateMessageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('createMessageForClub', 'clubId', clubId)
            // verify required parameter 'createMessageRequest' is not null or undefined
            assertParamExists('createMessageForClub', 'createMessageRequest', createMessageRequest)
            const localVarPath = `/api/clubs/{clubId}/Messages`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMessageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessagesForClub: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getMessagesForClub', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/Messages`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessagesApi - functional programming interface
 */
export const MessagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {CreateMessageRequest} createMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMessageForClub(clubId: string, createMessageRequest: CreateMessageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateMessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMessageForClub(clubId, createMessageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.createMessageForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessagesForClub(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAllMessagesByClubIdResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessagesForClub(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.getMessagesForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MessagesApi - factory interface
 */
export const MessagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessagesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {CreateMessageRequest} createMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMessageForClub(clubId: string, createMessageRequest: CreateMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateMessageResponse> {
            return localVarFp.createMessageForClub(clubId, createMessageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessagesForClub(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetAllMessagesByClubIdResponse>> {
            return localVarFp.getMessagesForClub(clubId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MessagesApi - object-oriented interface
 */
export class MessagesApi extends BaseAPI {
    /**
     * 
     * @param {string} clubId 
     * @param {CreateMessageRequest} createMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createMessageForClub(clubId: string, createMessageRequest: CreateMessageRequest, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).createMessageForClub(clubId, createMessageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMessagesForClub(clubId: string, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).getMessagesForClub(clubId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WorkPlansApi - axios parameter creator
 */
export const WorkPlansApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {CreateWorkPlanRequest} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWorkPlanForClub: async (clubId: string, createWorkPlanRequest: CreateWorkPlanRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('createWorkPlanForClub', 'clubId', clubId)
            // verify required parameter 'createWorkPlanRequest' is not null or undefined
            assertParamExists('createWorkPlanForClub', 'createWorkPlanRequest', createWorkPlanRequest)
            const localVarPath = `/api/clubs/{clubId}/WorkPlans`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createWorkPlanRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkPlansForClub: async (clubId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clubId' is not null or undefined
            assertParamExists('getWorkPlansForClub', 'clubId', clubId)
            const localVarPath = `/api/clubs/{clubId}/WorkPlans`
                .replace(`{${"clubId"}}`, encodeURIComponent(String(clubId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkPlansApi - functional programming interface
 */
export const WorkPlansApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WorkPlansApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {CreateWorkPlanRequest} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createWorkPlanForClub(clubId: string, createWorkPlanRequest: CreateWorkPlanRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateWorkPlanResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createWorkPlanForClub(clubId, createWorkPlanRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkPlansApi.createWorkPlanForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWorkPlansForClub(clubId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAllWorkPlansByClubIdResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkPlansForClub(clubId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkPlansApi.getWorkPlansForClub']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WorkPlansApi - factory interface
 */
export const WorkPlansApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WorkPlansApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clubId 
         * @param {CreateWorkPlanRequest} createWorkPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWorkPlanForClub(clubId: string, createWorkPlanRequest: CreateWorkPlanRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateWorkPlanResponse> {
            return localVarFp.createWorkPlanForClub(clubId, createWorkPlanRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clubId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkPlansForClub(clubId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetAllWorkPlansByClubIdResponse>> {
            return localVarFp.getWorkPlansForClub(clubId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkPlansApi - object-oriented interface
 */
export class WorkPlansApi extends BaseAPI {
    /**
     * 
     * @param {string} clubId 
     * @param {CreateWorkPlanRequest} createWorkPlanRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createWorkPlanForClub(clubId: string, createWorkPlanRequest: CreateWorkPlanRequest, options?: RawAxiosRequestConfig) {
        return WorkPlansApiFp(this.configuration).createWorkPlanForClub(clubId, createWorkPlanRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clubId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWorkPlansForClub(clubId: string, options?: RawAxiosRequestConfig) {
        return WorkPlansApiFp(this.configuration).getWorkPlansForClub(clubId, options).then((request) => request(this.axios, this.basePath));
    }
}



